version: '3.4'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: trip
       MYSQL_USER: trip
       MYSQL_PASSWORD: trip
     ports:
      - "3307:3306"
volumes:
    db_data: